name: 'google_fiber'
version: '1.0.0'
config-version: 2

profile: 'google_fiber'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  google_fiber:
    staging:
      +materialized: view
    marts:
      +materialized: table
